import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { QueryProvider } from "@/components/providers/query-provider";
import AuthProvider from "@/components/providers/auth-provider";
import { ModalProvider } from "@/components/providers/modal-provider";

const font = Public_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Job tracker",
    template: "%s | Job tracker",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased bg-bg`}>
        <QueryProvider>{children}</QueryProvider>
        <ModalProvider />
        <Toaster richColors />
      </body>
    </html>
  );
}
