import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const font = Public_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Job tracker",
    template: "%s | Job tracker",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
